<?php

use Livewire\Component;

new class extends Component
{
    //
};
?>

<x-card.card-container
        title="Field Suggested"
        subtitle="That's a suggestion made by the AI in which field the user can be"
        class="text-wrap"
>
    {{-- TAG TO SHOW THAT THE SUMMARY HAS BEEN GENERATED BY AI --}}
    <x-tag
            variant="white"
            icon="sparkles"
            size="sm"
    >
        AI SUGGESTION
    </x-tag>
</x-card.card-container>