<?php

use App\Domain\Skill\Contracts\SkillAssignable;
use App\Domain\User\Factory\UserServiceFactory;
use App\Domain\User\Services\UserService;
use Livewire\Attributes\Lazy;
use Livewire\Component;

new #[Lazy]
class extends Component {

    public ?SkillAssignable $user = null;

    public ?string $suggestedField = null;
    public ?string $fieldDescription = null;

    public bool $isGenerating = false;

    /**
     * Load the UserServiceFactory to return the instance of UserService, with make method,
     * then it will the field from the service.
     *
     * The field it's empty that means it generates a new one, otherwise,
     * it will take the one from the getField() method.
     * */
    public function mount(
        UserServiceFactory $factory
    ): void
    {
        if(!$this->user || !$this->user->hasSkill()) return ;


        $userService = $factory->make($this->user);
        $this->hydrateField($userService->getField());

        if ($this->suggestedField === null) {
            $userService->generateUserFieldSuggest();
        }
    }

    /**
     * This method acts as the mount, but it will be used by
     * livewire to check if the field has been generated from the
     * AI or not.
     * */
    public function refreshFieldSuggestion(UserServiceFactory $factory): void
    {
        if ($this->suggestedField !== null) {
            $this->isGenerating = false;
            return;
        }

        $userService = $factory->make($this->user);
        $this->hydrateField($userService->getField());
        $this->isGenerating = $this->field === '';
    }

    /**
     * Method to convert the result of the OpenAI response
     * from JSON, to save the key of the result into
     * two separate attributes, one for the field,
     * one for the field description.
    **/
    private function hydrateField(string $raw): void
    {
        if ($raw === '') return;

        $decoded = json_decode($raw, true);
        if (json_last_error() !== JSON_ERROR_NONE) return;

        $this->suggestedField = $decoded['suggested_field'] ?? null;
        $this->fieldDescription = $decoded['description'] ?? null;
    }

    /**
     * Placeholder method to show when the response of OpenAI's working.
     * */
    public function placeholder(): string
    {
        return <<<'HTML'
                <x-card.card-container
                        title="Field Suggested"
                        subtitle="That's a suggestion made by the AI in which field the user can ber"
                >
                    <div class="summary-skeleton">
                        <div class="skeleton-line"></div>
                        <div class="skeleton-line skeleton-line--short"></div>
                        <div class="skeleton-line"></div>
                    </div>
                </x-card.card-container>
        HTML;
    }
};
?>

<x-card.card-container
        title="Field Suggested"
        subtitle="That's a suggestion made by the AI in which field the user can be"
        class="text-wrap"
>
    {{-- REFRESH THE PAGE TO FETCH THE SUMMARY   --}}
    @if($isGenerating)
        <div wire:poll.2s="refreshFieldSuggestion"></div>
    @endif

    @if($this->user->hasSkill())
        @if($suggestedField !== null)
            {{--   SHOW THE RESULT OF THE FIELD SUGGESTED AND DESCRIPTION    --}}
            <p class="font-semibold text-xl">{{ $suggestedField }}</p>
            <p class="indent-0 text-lg ">{{ trim($fieldDescription) }}</p>

            {{-- TAG TO SHOW THAT THE SUMMARY HAS BEEN GENERATED BY AI --}}
            <x-tag
                    variant="white"
                    icon="sparkles"
                    size="sm"
            >
                AI SUGGESTION
            </x-tag>
        @else
            {{--   SHOW THE PLACEHOLDER IF THE FIELD IT'S STILL EMPTY     --}}
            <div class="summary-skeleton">
                <div class="skeleton-line"></div>
                <div class="skeleton-line skeleton-line--short"></div>
            </div>
        @endif
    @else
        <x-empty-state
                icon="cube-transparent"
                message="This customer has no skill added yet"
                description="Add a skill or schema to this customer to get feedback about it"
        />
    @endif
</x-card.card-container>