<?php

use App\Domain\Skill\Contracts\SkillAssignable;
use App\Domain\Skill\Services\SkillService;
use App\Domain\User\Services\UserService;
use App\Jobs\GenerateUserReview;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Collection;
use Livewire\Attributes\Lazy;
use Livewire\Component;

new #[Lazy]
class extends Component {

    public ?SkillAssignable $user = null;
    public ?string $summary = '';
    public ?array $skills = null;
    public bool $isGenerating = false;

    public function mount(): void
    {
        if(!$this->user) return;

        if ($this->user->hasSkill()) {
            $userService = new UserService($this->user);
            $this->summary = $userService->getReview();

            if ($this->summary === '') {
                $userService->generateUserReview();
                $this->summary = $userService->getReview();
                $this->isGenerating = $this->summary === '';
            }
        }
    }

    public function refreshSummary(): void
    {
        if (!$this->user->hasSkill()) {
            $this->isGenerating = false;
            return;
        }

        $userService = new UserService($this->user);
        $this->summary = $userService->getReview();
        $this->isGenerating = $this->summary === '';
    }

    public function placeholder(): string
    {
        return <<<'HTML'
                <x-card.card-container
                        title="Summary"
                        subtitle="That's a quick review about the customer"
                >
                    <div class="summary-skeleton">
                        <div class="skeleton-line"></div>
                        <div class="skeleton-line skeleton-line--short"></div>
                        <div class="skeleton-line"></div>
                    </div>
                </x-card.card-container>
        HTML;
    }
};
?>

<x-card.card-container
        title="Summary"
        subtitle="That's a quick review about the customer"
        class="text-wrap"
>

    {{-- REFRESH THE PAGE TO FETCH THE SUMMARY   --}}
    @if($isGenerating)
        <div wire:poll.2s="refreshSummary"></div>
    @endif

    {{-- JUST SHOW THE SUMMARY ONLY IF THE CUSTOME HAS IT --}}
    @if($this->user->hasSkill())
        @if($summary !== '')
            @php
                $summaryLines = preg_split('/\r\n|\r|\n/', trim($summary));
            @endphp
            <div class="space-y-3">
                @foreach($summaryLines as $line)
                    @if(trim($line) !== '')
                        <p class="indent-0 text-lg text-wrap">{{ $line }}</p>
                    @endif
                @endforeach
            </div>

            {{-- TAG TO SHOW THAT THE SUMMARY HAS BEEN GENERATED BY AI --}}
            <x-tag
                    variant="white"
                    icon="sparkles"
                    size="sm"
            >
                AI SUMMARY
            </x-tag>
        @else
            <div class="summary-skeleton">
                <div class="skeleton-line"></div>
                <div class="skeleton-line skeleton-line--short"></div>
                <div class="skeleton-line"></div>
            </div>
        @endif
    @else
        <x-empty-state
                icon="cube-transparent"
                message="This customer has no skill added yet"
                description="Add a skill or schema to this customer to get an evaluation"
        />
    @endif
</x-card.card-container>
